<template>
  <div>
    <Navbar :fixed_navbar="true"/>
    <ReusableContainer :top_spacing="true">
      <h1>Primer H1</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus placeat quisquam omnis. Aspernatur repellat earum facere sapiente, libero praesentium dicta odit in unde doloremque repellendus modi quo ratione at consectetur? Laborum est non repellendus, eveniet explicabo ipsa illo necessitatibus quae tempore vel cupiditate doloremque, iure saepe, voluptatum dolore veritatis totam neque corporis repudiandae distinctio. Inventore libero beatae quos tempora aspernatur!</h1>
    </ReusableContainer>
  </div>
</template>

<script>
export default {
  name: 'projects',
  nuxtI18n: {
    paths: {
      es: '/proyectos',
      en: '/projects'
    }
  }
}
</script>

<style>

</style>
